# Top-level configuration
name = "my-worker"
main = ".open-next/worker.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

workers_dev = false
route = { pattern = "example.org/*", zone_name = "example.org" }

kv_namespaces = [
  { binding = "<MY_NAMESPACE>", id = "<KV_ID>" }
]

[env.staging]
name = "my-worker-staging"
route = { pattern = "staging.example.org/*", zone_name = "example.org" }

kv_namespaces = [
  { binding = "<MY_NAMESPACE>", id = "<STAGING_KV_ID>" }
]
